//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Resource.CustomMessage", typeof(CustomMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ نامه خالی است.
        /// </summary>
        internal static string AnswerInsurancePolicies {
            get {
                return ResourceManager.GetString("AnswerInsurancePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما مسدود است.
        /// </summary>
        internal static string BlockUserAccount {
            get {
                return ResourceManager.GetString("BlockUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش پیش فرض یافت نشد.
        /// </summary>
        internal static string DefaultRoleNotFound {
            get {
                return ResourceManager.GetString("DefaultRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف تصویر با خطا مو.اجه شد.
        /// </summary>
        internal static string ErrorRemoveOldImage {
            get {
                return ResourceManager.GetString("ErrorRemoveOldImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اعتبار سنجی منقضی شده است.
        /// </summary>
        internal static string ExpiryRegisterCode {
            get {
                return ResourceManager.GetString("ExpiryRegisterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم تکراری است..
        /// </summary>
        internal static string ExsitOnDateBase {
            get {
                return ResourceManager.GetString("ExsitOnDateBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی رخ داده است.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با کدملی قبلا ثبت نام شده است.
        /// </summary>
        internal static string NationalCodeExist {
            get {
                return ResourceManager.GetString("NationalCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در دیتابیس موجودیت یافت نشد.
        /// </summary>
        internal static string NotFoundOnDb {
            get {
                return ResourceManager.GetString("NotFoundOnDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اعتبارسنجی نامعتبر است.
        /// </summary>
        internal static string OtpCodeNotValide {
            get {
                return ResourceManager.GetString("OtpCodeNotValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ثبت نام کاربر رخ داده است.
        /// </summary>
        internal static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی الزامی است.
        /// </summary>
        internal static string RequiredCategory {
            get {
                return ResourceManager.GetString("RequiredCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب شهر الزامی است.
        /// </summary>
        internal static string RequiredCityId {
            get {
                return ResourceManager.GetString("RequiredCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب شرکت بیمه الزامی است.
        /// </summary>
        internal static string RequiredCompany {
            get {
                return ResourceManager.GetString("RequiredCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب تاریخ الزامی است.
        /// </summary>
        internal static string RequiredDateTime {
            get {
                return ResourceManager.GetString("RequiredDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز الزامی است.
        /// </summary>
        internal static string RequiredDay {
            get {
                return ResourceManager.GetString("RequiredDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات الزامی است.
        /// </summary>
        internal static string RequiredDescription {
            get {
                return ResourceManager.GetString("RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام الزامی است.
        /// </summary>
        internal static string RequiredFirstName {
            get {
                return ResourceManager.GetString("RequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام انگلیسی الزامی است.
        /// </summary>
        internal static string RequiredFirstNameEn {
            get {
                return ResourceManager.GetString("RequiredFirstNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت الزامی است.
        /// </summary>
        internal static string RequiredGender {
            get {
                return ResourceManager.GetString("RequiredGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فیلد الزامی است.
        /// </summary>
        internal static string RequiredInputType {
            get {
                return ResourceManager.GetString("RequiredInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی الزامی است.
        /// </summary>
        internal static string RequiredLastName {
            get {
                return ResourceManager.GetString("RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی الزامی است.
        /// </summary>
        internal static string RequiredLastNameEn {
            get {
                return ResourceManager.GetString("RequiredLastNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلاک الزامی است.
        /// </summary>
        internal static string RequiredLicensePlateNumber {
            get {
                return ResourceManager.GetString("RequiredLicensePlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه الزامی است.
        /// </summary>
        internal static string RequiredMonth {
            get {
                return ResourceManager.GetString("RequiredMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام الزامی است..
        /// </summary>
        internal static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی الزامی است.
        /// </summary>
        internal static string RequiredNationalCode {
            get {
                return ResourceManager.GetString("RequiredNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی الزامی است..
        /// </summary>
        internal static string RequiredPersianName {
            get {
                return ResourceManager.GetString("RequiredPersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه الزامی است.
        /// </summary>
        internal static string RequiredPhoneNumber {
            get {
                return ResourceManager.GetString("RequiredPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب استان الزامی است.
        /// </summary>
        internal static string RequiredProvinceId {
            get {
                return ResourceManager.GetString("RequiredProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه فیلد الزامی است.
        /// </summary>
        internal static string RequiredQuestionId {
            get {
                return ResourceManager.GetString("RequiredQuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الزامی است.
        /// </summary>
        internal static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نوع بیمه الزامی است.
        /// </summary>
        internal static string RequiredType {
            get {
                return ResourceManager.GetString("RequiredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر الزامی است.
        /// </summary>
        internal static string RequiredUserId {
            get {
                return ResourceManager.GetString("RequiredUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال الزامی است.
        /// </summary>
        internal static string RequiredYear {
            get {
                return ResourceManager.GetString("RequiredYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا چند نقش به کاربر اختصاص دهید.
        /// </summary>
        internal static string RolesForUser {
            get {
                return ResourceManager.GetString("RolesForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        internal static string SuccessAction {
            get {
                return ResourceManager.GetString("SuccessAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجوز دسترسی را ندارید.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری یافت نشد.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
